### ISSUE TITLE
publish on bower

### ISSUE THREAD

**Issue by duongphuhiep** [jimsparkman/RiotControl#11]
Please publish it on [bower](http://bower.io/), riot and RiotControl packages are for front-end development, so bower is a more adapted repository. Also client-side module loader works better on bower than npm.

thank you

**Comment by vojtabiberle** [comment]
I will too appreciate bower package.

**Comment by vojtabiberle** [comment]
https://github.com/jimsparkman/RiotControl/pull/14

**Comment by optikfluffel** [comment]
:+1:

**Comment by jimsparkman** [comment]
Merged #14

**Comment by vojtabiberle** [comment]
Thanks man!

**Comment by jimsparkman** [comment]
No problem, thank you.

**Comment by vojtabiberle** [comment]
I have question: Why is bower package linked to some fork of RiotControl? riotcontrol git://github.com/hongbinfu/RiotControl.git

**Comment by avimar** [comment]
Weird, I had that same issue.

I installed using `bower install jimsparkman/RiotControl`
