### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by icetan** [jimsparkman/RiotControl#2]
I can't find under which license you have released this very nice project.

Even though it is a common pattern it would be nice to make it obvious to what license this repo is under.

**Comment by jimsparkman** [comment]
Hadn't thought much about it, what do you suggest? MIT?

**Comment by icetan** [comment]
MIT or ISC which is also very popular in the JavaScript community, I think it's even the default license when you run `npm init`.

But MIT is more recognisable and thus it might be easier for people to use your project.
