### ISSUE TITLE
Add 'reset' or 'destroy' method

### ISSUE THREAD

**Issue by fishermand46** [jimsparkman/RiotControl#21]
When testing, it is very nice to be able to reset your global dispatch object (in this case RiotControl).

We could add a method `destroy` which would probably just set the internal stores variable equal to `[]`.

I'd be happy to open a PR if this is something you think would be worth adding.

**Comment by fishermand46** [comment]
Dupe of #12 .

**Comment by jimsparkman** [comment]
I think it's a good idea, it is worth adding. Send me a PR and I'll merge it.
