### ISSUE TITLE
Multiples instances of the same tag

### ISSUE THREAD

**Issue by aRandomKiwi** [jimsparkman/RiotControl#26]
Hi, RiotControl dont support multiples instances of the same tag handled by one store, did you find a workaround ?

**Comment by re1ro** [comment]
@Mariick you have to come up with unique namespaces for your events.
Like `action:tagName` for all similar tags or `action:tagName:tagInstanceID` for specific instance of a tag.

**Comment by aRandomKiwi** [comment]
Thank you @rma4ok ,   @jimsparkman  already answer me in another thread on RiotJS's github ([https://github.com/riot/riot/issues/1312#issuecomment-156885632](https://github.com/riot/riot/issues/1312#issuecomment-156885632)) , i just forget to close this one.
