### ISSUE TITLE
[QUESTION] What you think about riotux? 

### ISSUE THREAD

**Issue by luisvinicius167** [jimsparkman/RiotControl#31]
Hi, what you think about riotux Event Controller?

> **riotux** provides more organization for datastore in your application. Your Stores can call and listen events to other Stores and Components, that can call and listen events to Stores too. The Dispatcher is used to communicate between Components.

Thanks!

**Comment by a-moses** [comment]
hay what the different between  riotux to RiotControl
 ?
update:
Thank you @luisvinicius167

**Comment by luisvinicius167** [comment]
@a-moses, riotux provides more organization for datastore in your application. In RiotControl if you has 2 Stores listening the event 'add_todo' and when you use RiotControl.trigger('add_todo'), your 2 stores will listen and trigger the callback. But imagine that you just want trigger the 'add_todo' to Store A, you don't get. 

With riotux , you can! Just pass the Store Name. riotux.trigger('StoreA', 'add_todo') and just the Store A will send the callback. This way, you don't be lost. Read the Readme.md for you know about riotux :)

**Comment by jimsparkman** [comment]
Clean and simple, I like it!

**Comment by luisvinicius167** [comment]
@jimsparkman, nice! :)
