### ISSUE TITLE
demo todo

### ISSUE THREAD

**Issue by cristinallamas** [jimsparkman/RiotControl#35]
https://github.com/jimsparkman/RiotControl/blob/master/demo/todo.tag#L20-L57

Is there a reason for the repetition of this here without script tags? I'm trying to make this demo work but I can't figure out why is not working.

Thanks in advance.

Riot Learner

**Comment by jimsparkman** [comment]
The .tag get 'compiled' by riot into a .js file that is included with a script tag. Keep in mind this is built using an older version of riot and things seem to evolve quickly over there.
