### ISSUE TITLE
this isn't in npm

### ISSUE THREAD

**Issue by mark-hahn** [jimsparkman/RiotControl#6]
I'll copy the code for now but it would be nice to keep it up-to-date using package.json.

**Comment by jimsparkman** [comment]
Is this not working? https://www.npmjs.com/package/riotcontrol

You should be able to 'npm install riotcontrol'

**Comment by mark-hahn** [comment]
Yes, it all seems fine.  I don't know why I couldn't find it before.  I
think maybe I did a search for riot-control which found nothing.

Sorry to bother you.

**Comment by jimsparkman** [comment]
No problem at all!
