### ISSUE TITLE
Urls are not bookmarkable

### ISSUE THREAD

**Issue by simoami** [jimsparkman/RiotControl#8]
if you copy a given url route and load it on a blank page or simply refresh the browser page, the view is not regenerated.

**Comment by MauriSalazar** [comment]
+1

**Comment by r4j4h** [comment]
[This is reproducible](http://jimsparkman.github.io/RiotControl/routing_demo/) as [this link should take you to item 2](http://jimsparkman.github.io/RiotControl/routing_demo/#view/2) but that's an example and pageload hashtag parsing was probably just left out for clarity so as to not distract from RiotControl which is actually just highlighted in a few of those files, or are you guys describing something else?

**Comment by jimsparkman** [comment]
I think this is something important for the example to demonstrate, if I can find time I will add it.

**Comment by BlackBooth** [comment]
Got a solution for this. I sent you a PR. #15

**Comment by jimsparkman** [comment]
Merged #15
